version: '3'

services:
    reciper_nginx:
        container_name: reciper_nginx
        image: serhiicho/reciper:nginx
        networks:
            - reciper_net
        volumes:
            - ./frontend/dist:/app/dist
            - ./backend/storage:/app/dist/storage
        environment:
            GO111MODULE: "on"
        ports:
            - 8000:80
        depends_on:
            - reciper_go

    reciper_go:
        container_name: reciper_go
        image: serhiicho/reciper:go
        networks:
            - reciper_net
        ports:
            - 8080:8080
        links:
            - reciper_db

    reciper_db:
        image: mysql:8.0
        container_name: reciper_db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 111111
            MYSQL_DATABASE: reciper
        ports:
            - 1001:3306
        volumes:
            - ./db/storage:/var/lib/mysql
        networks:
            - reciper_net

    reciper_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: reciper_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 1221:80
        depends_on:
            - reciper_db
        networks:
            - reciper_net

networks:
    reciper_net:
        driver: bridge