version: '3'

services:
    # reciper_db:
    #     image: mysql:8.0
    #     container_name: reciper_db
    #     command: --default-authentication-plugin=mysql_native_password
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 111111
    #         MYSQL_DATABASE: reciper
    #     ports:
    #         - 1000:3306
    #     volumes: 
    #         - ./db/storage:/var/lib/mysql
    #     networks:
    #         - reciper_net

    reciper_go:
        container_name: reciper_go
        image: serhiicho/reciper:go
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
            - reciper_net
        ports:
            - 8080:8080
        depends_on:
            - reciper_node
        # depends_on:
        #     - reciper_db
        # links:
        #     - reciper_db

    reciper_node:
        image: node:8-alpine
        container_name: reciper_node
        working_dir: /app/app
        volumes:
            - ./app:/app/app
        command: sh -c "npm i && npm audit fix && npm rebuild node-sass && yarn build"

networks:
    reciper_net:
        driver: bridge