version: '3'

services:
    # reciper_db:
    #     image: mysql:8.0
    #     container_name: reciper_db
    #     command: --default-authentication-plugin=mysql_native_password
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 111111
    #         MYSQL_DATABASE: reciper
    #     ports:
    #         - 1000:3306
    #     volumes: 
    #         - ./db/storage:/var/lib/mysql
    #     networks:
    #         - reciper_net

    reciper_nginx:
        container_name: reciper_nginx
        image: serhiicho/reciper:nginx
#        build:
#            context: frontend/
#            dockerfile: Dockerfile
        networks:
            - reciper_net
        volumes:
            - ./frontend/dist:/app/dist
        ports:
            - 8000:80
        depends_on:
            - reciper_go

    reciper_go:
        container_name: reciper_go
        image: serhiicho/reciper:go
#        build:
#            context: ./backend
#            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
            - reciper_net
        ports:
            - 8080:8080
        # links:
        #     - reciper_db

networks:
    reciper_net:
        driver: bridge